Lessons/lesson_08_01_blog/ViewModels/GetPublicationViewModel.cs
using lesson_08_01_blog.Models;

namespace lesson_08_01_blog.ViewModels;

public class GetPublicationViewModel
{
    public Publication Publication {get; set; }
    public string? ReturnUrl { get; set; }
}

Lessons/lesson_08_01_blog/Controllers/HomeController.cs
using System.Diagnostics;
using lesson_08_01_blog.Interfaces;
using Microsoft.AspNetCore.Mvc;
using lesson_08_01_blog.Models;
using lesson_08_01_blog.ViewModels;

namespace lesson_08_01_blog.Controllers;

public class HomeController : Controller
{
    public readonly ICategory _categories;
    public readonly IPublication _publications;
    public readonly IWebHostEnvironment _appEnvironment;
    
    public HomeController(ICategory categories, IPublication publications, IWebHostEnvironment appEnvironment)
    {
        _categories = categories;
        _publications = publications;
        _appEnvironment = appEnvironment;
    }

    public async Task<IActionResult> Index(QueryOptions? options, string? categoryId)
    {
        var allCategories = await _categories.GetAllCategoriesAsync();
        var allPublications = await _publications.GetAllPublicationsByCategoriesAsync(options, categoryId);

        return View(new IndexViewModel()
        {
            Categories = allCategories.ToList(),
            Publications = allPublications
        });
    }

    [Route("publication")]
    public async Task<IActionResult> GetPublication(string? id, string? returnUrl)
    {
        var currentPublication = await _publications.GetPublicationWithCategoriesAsync(id);
        if (currentPublication is not null)
        {
            await _publications.UpdateViewsAsync(currentPublication.Id.ToString());
            return View(new GetPublicationViewModel()
            {
                Publication = currentPublication,
                ReturnUrl = returnUrl
            });
        }

        return NotFound();
    }
}

Lessons/lesson_08_01_blog/ViewComponents/AdditionalPublicationsViewComponent.cs
using lesson_08_01_blog.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace lesson_08_01_blog.ViewComponents;

public class AdditionalPublicationsViewComponent : ViewComponent
{
    private readonly IPublication _publication;

    public AdditionalPublicationsViewComponent(IPublication publication)
    {
        _publication = publication;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var publications = await _publication.GetRandomPublications();
        
        return await Task.FromResult((IViewComponentResult)View("AdditionalPublications", publications));
    }
}

Lessons/lesson_08_01_blog/Views/Home/GetPublication.cshtml
@model lesson_08_01_blog.ViewModels.GetPublicationViewModel
 
@{
    ViewBag.Title = Model.Publication.Title;
    ViewBag.Description = Model.Publication.SeoDescription;
    ViewBag.Keywords = Model.Publication.Keywords;
}
 
<div class="p-4 p-md-5 mb-4 text-white rounded" style="background-image: linear-gradient( to bottom, rgba(0, 0, 255, 0.5), rgb(162 162 0 / 50%) )">
    <div class="col-md-12 px-0">
        <h1 class="display-4 fst-italic">@Model.Publication.Title</h1>
    </div>
    <div class="small mb-1">
        <a href="@(Model.ReturnUrl ??= Url.Action(action: "Index", controller: "Home",
                    values: null, protocol: "https"))">« Вернутся назад</a>
    </div>
</div>
 
<div class="row g-5">
    <div class="col-md-8">
        <p class="fst-italic">
            <a href="@Url.Action(action: "Index", controller: "Home", values: null, protocol: "https")">Главная</a>
            « @Model.Publication.Title
        </p>
        <p class="pb-4 mb-4 fst-italic border-bottom">
            Категории:
            @foreach (Category category in Model.Publication.Categories)
            {
                <a href="@Url.Action(action: "Index", controller: "Home", values: new { categoryId = category.Id }, protocol: "https")">@category.Name</a>
            }
        </p>
        <img src="@Model.Publication.Image" class="img-fluid" alt="Responsive image">
        <article class="blog-post">
            @Html.Raw(Model.Publication.Description)
        </article>
 
    </div>
 
    <div class="col-md-4">
        <div class="position-sticky" style="top: 2rem;">
            <div class="p-4 mb-3 bg-light rounded">
                <p class="mb-0">Дата публикации: <b>@Model.Publication.CreatedAt.ToShortDateString()</b></p>
                <p class="mb-0">
                    Всего просмотров:
                    <b>@Model.Publication.TotalViews</b>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                    </svg>
                </p>
                <p class="mb-0">
                    <br />
                    Авторское право – это юридический термин, используемый для описания прав, которыми
                    обладают авторы на свои литературные и художественные произведения.
                </p>
            </div>
 
            <div class="p-4">
                <h4 class="fst-italic">Архивы</h4>
                <ol class="list-unstyled mb-0">
                    <li><a href="#">Март 2022</a></li>
                    <li><a href="#">Февраль 2022</a></li>
                    <li><a href="#">Январь 2022</a></li>
                    <li><a href="#">Декабрь 2022</a></li>
                </ol>
            </div>
 
            <div class="p-4 mb-3 bg-light rounded">
                <h4 class="fst-italic">Рекламный блок</h4>
                <p class="mb-0">
                    Этот рекламный слоган создали в 1997 году в ответ на девиз «Think» прямого конкурента Apple — IBM.
                    По данным Forbes, через год после запуска слогана «Think Different» акции компании выросли втрое,
                    хотя новых значимых продуктов она не выпускала.
                </p>
            </div>
 
            <div class="p-4">
                <h4 class="fst-italic">Мои сети</h4>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                </ol>
            </div>
 
        </div>
    </div>
</div>
<div class="row mt-3">
    <vc:additional-publications></vc:additional-publications>
</div>

Lessons/lesson_08_01_blog/Views/Home/Index.cshtml
@using lesson_08_01_blog.Helpers
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model lesson_08_01_blog.ViewModels.IndexViewModel
@{
    ViewData["Title"] = "Блог";
    ViewData["Description"] = "Блог о путешествиях, рассказы из жизни.";
    ViewData["Keywords"] = "путешествия, истории жизни.";
}
 
<link rel="stylesheet" href="~/css/book/home.css" asp-append-version="true" />
 
<header class="py-5" style="background-image: linear-gradient( to bottom, rgba(0, 0, 255, 0.5), rgb(162 162 0 / 50%) )">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Блог</h1>
            <p class="lead fw-normal text-white-50 mb-0"> У настоящего путешественника нет определенного плана и намерения куда-либо приехать </p>
        </div>
    </div>
</header>
 
<div class="container my-5">
    <div class="row">
        <div class="col-lg-3">
 
            @{
                ViewBag.sorts = new string[] { "", "Title", "TotalViews", "CreatedAt" };
            }
 
            @await Html.PartialAsync("_PageOptions", Model.Publications)
 
            <!-- Categories widget-->
            <div class="card mb-4">
                <div class="card-header">Жанры</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                @for (int i = 0; i < Model.Categories.Count / 2; i++)
                                {
                                    <li><a href="@Url.Action(action: "Index", controller: "Home", values: new { categoryId = Model.Categories[i].Id }, protocol: "https")">@Model.Categories[i].Name</a></li>
                                }
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                @for (int i = Model.Categories.Count / 2; i < Model.Categories.Count; i++)
                                {
                                    <li><a href="@Url.Action(action: "Index", controller: "Home", values: new { categoryId = Model.Categories[i].Id }, protocol: "https")">@Model.Categories[i].Name</a></li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
 
            <!-- Side widget-->
            <div class="card mb-4">
                <div class="card-header">Рекламный блок</div>
                <div class="card-body">Здесь могла быть ваша реклама.</div>
            </div>
        </div>
 
        <div class="col-lg-9">
 
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-2 justify-content-center">
 
                @foreach (Publication publication in Model.Publications)
                {
                    <div class="col mb-5">
                        <div class="card h-100">
                            @if (@publication.Image != null)
                            {
                                <img class="card-img-top book-preview" src="@publication.Image" alt="@publication.Title">
                            }
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">@publication.Title</h5>
                                    <span>@String.Join(", ", publication.Categories.Select(e => e.Name))</span>
                                    <div>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                                            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                                        </svg>
                                        <span>@publication.TotalViews</span>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto" href="@Url.Action(action: "GetPublication", controller: "Home",
                                    values: new { id = publication.Id, returnUrl = ViewContext.HttpContext.Request.PathAndQuery() }, protocol: "https")">Читать</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
 
            </div>
 
            <div class="text-center">
                @await Html.PartialAsync("_Pages", Model)
            </div>
 
        </div>
    </div>
</div>